-- Seed Tags para Supabase
-- Execute este script no SQL Editor do Supabase Dashboard
-- Após executar a migração (migration.sql)

-- Limpar tabela de tags (opcional - descomente se quiser limpar antes)
-- DELETE FROM tags;

-- Inserir tags
INSERT INTO tags (name, category, parent_id) VALUES
-- Tecnologia - Categorias principais
('Tecnologia', 'Tecnologia', NULL),
('Frontend', 'Tecnologia', NULL),
('Backend', 'Tecnologia', NULL),
('Mobile', 'Tecnologia', NULL),
('DevOps', 'Tecnologia', NULL),
('Data Science', 'Tecnologia', NULL),
('Segurança', 'Tecnologia', NULL),
('Cloud Computing', 'Tecnologia', NULL),
('QA/Testes', 'Tecnologia', NULL),
('Arquitetura de Software', 'Tecnologia', NULL),

-- Frontend
('React', 'Tecnologia', NULL),
('Vue.js', 'Tecnologia', NULL),
('Angular', 'Tecnologia', NULL),
('JavaScript', 'Tecnologia', NULL),
('TypeScript', 'Tecnologia', NULL),
('HTML', 'Tecnologia', NULL),
('CSS', 'Tecnologia', NULL),
('SASS/SCSS', 'Tecnologia', NULL),
('Tailwind CSS', 'Tecnologia', NULL),
('Next.js', 'Tecnologia', NULL),
('Nuxt.js', 'Tecnologia', NULL),
('Svelte', 'Tecnologia', NULL),

-- Backend
('Node.js', 'Tecnologia', NULL),
('Python', 'Tecnologia', NULL),
('Java', 'Tecnologia', NULL),
('C#', 'Tecnologia', NULL),
('PHP', 'Tecnologia', NULL),
('Ruby', 'Tecnologia', NULL),
('Go', 'Tecnologia', NULL),
('Rust', 'Tecnologia', NULL),
('Django', 'Tecnologia', NULL),
('Flask', 'Tecnologia', NULL),
('Spring Boot', 'Tecnologia', NULL),
('Express.js', 'Tecnologia', NULL),
('Laravel', 'Tecnologia', NULL),
('ASP.NET', 'Tecnologia', NULL),

-- Mobile
('React Native', 'Tecnologia', NULL),
('Flutter', 'Tecnologia', NULL),
('Swift', 'Tecnologia', NULL),
('Kotlin', 'Tecnologia', NULL),
('iOS', 'Tecnologia', NULL),
('Android', 'Tecnologia', NULL),
('Xamarin', 'Tecnologia', NULL),
('Ionic', 'Tecnologia', NULL),

-- DevOps
('Docker', 'Tecnologia', NULL),
('Kubernetes', 'Tecnologia', NULL),
('AWS', 'Tecnologia', NULL),
('Azure', 'Tecnologia', NULL),
('GCP', 'Tecnologia', NULL),
('CI/CD', 'Tecnologia', NULL),
('Jenkins', 'Tecnologia', NULL),
('GitLab CI', 'Tecnologia', NULL),
('GitHub Actions', 'Tecnologia', NULL),
('Terraform', 'Tecnologia', NULL),
('Ansible', 'Tecnologia', NULL),

-- Data Science
('Machine Learning', 'Tecnologia', NULL),
('Deep Learning', 'Tecnologia', NULL),
('Data Analysis', 'Tecnologia', NULL),
('Big Data', 'Tecnologia', NULL),
('SQL', 'Tecnologia', NULL),
('PostgreSQL', 'Tecnologia', NULL),
('MySQL', 'Tecnologia', NULL),
('MongoDB', 'Tecnologia', NULL),
('Redis', 'Tecnologia', NULL),
('Pandas', 'Tecnologia', NULL),
('NumPy', 'Tecnologia', NULL),
('TensorFlow', 'Tecnologia', NULL),
('PyTorch', 'Tecnologia', NULL),

-- Design
('Design', 'Design', NULL),
('UI/UX Design', 'Design', NULL),
('Design Gráfico', 'Design', NULL),
('Web Design', 'Design', NULL),
('Motion Graphics', 'Design', NULL),
('Design de Produto', 'Design', NULL),
('Design de Interiores', 'Design', NULL),
('Figma', 'Design', NULL),
('Adobe Photoshop', 'Design', NULL),
('Adobe Illustrator', 'Design', NULL),
('Adobe XD', 'Design', NULL),
('Sketch', 'Design', NULL),
('InDesign', 'Design', NULL),
('After Effects', 'Design', NULL),
('Premiere Pro', 'Design', NULL),

-- Produção
('Produção', 'Produção', NULL),
('Operador de Máquinas', 'Produção', NULL),
('Controle de Qualidade', 'Produção', NULL),
('Logística', 'Produção', NULL),
('Almoxarifado', 'Produção', NULL),
('Produção Industrial', 'Produção', NULL),
('Manutenção Industrial', 'Produção', NULL),
('Soldagem', 'Produção', NULL),
('Usinagem', 'Produção', NULL),
('Montagem', 'Produção', NULL),
('Embalagem', 'Produção', NULL),
('Expedição', 'Produção', NULL),
('Gestão de Produção', 'Produção', NULL),
('Lean Manufacturing', 'Produção', NULL),

-- Agricultura
('Agricultura', 'Agricultura', NULL),
('Agronomia', 'Agricultura', NULL),
('Pecuária', 'Agricultura', NULL),
('Irrigação', 'Agricultura', NULL),
('Agricultura Orgânica', 'Agricultura', NULL),
('Agronegócio', 'Agricultura', NULL),
('Técnico Agrícola', 'Agricultura', NULL),
('Operador de Máquinas Agrícolas', 'Agricultura', NULL),
('Veterinária', 'Agricultura', NULL),
('Zootecnia', 'Agricultura', NULL),
('Silvicultura', 'Agricultura', NULL),
('Apicultura', 'Agricultura', NULL),

-- Limpeza
('Limpeza', 'Limpeza', NULL),
('Limpeza Industrial', 'Limpeza', NULL),
('Limpeza Doméstica', 'Limpeza', NULL),
('Limpeza Hospitalar', 'Limpeza', NULL),
('Limpeza Comercial', 'Limpeza', NULL),
('Zeladoria', 'Limpeza', NULL),
('Conservação', 'Limpeza', NULL),
('Auxiliar de Limpeza', 'Limpeza', NULL),

-- Saúde
('Saúde', 'Saúde', NULL),
('Enfermagem', 'Saúde', NULL),
('Medicina', 'Saúde', NULL),
('Fisioterapia', 'Saúde', NULL),
('Nutrição', 'Saúde', NULL),
('Psicologia', 'Saúde', NULL),
('Farmácia', 'Saúde', NULL),
('Odontologia', 'Saúde', NULL),
('Radiologia', 'Saúde', NULL),
('Biomedicina', 'Saúde', NULL),
('Fonoaudiologia', 'Saúde', NULL),
('Terapia Ocupacional', 'Saúde', NULL),
('Técnico em Enfermagem', 'Saúde', NULL),
('Auxiliar de Enfermagem', 'Saúde', NULL),
('Recepcionista de Clínica', 'Saúde', NULL),

-- Educação
('Educação', 'Educação', NULL),
('Pedagogia', 'Educação', NULL),
('Ensino Superior', 'Educação', NULL),
('EAD', 'Educação', NULL),
('Professor', 'Educação', NULL),
('Coordenador Pedagógico', 'Educação', NULL),
('Diretor de Escola', 'Educação', NULL),
('Instrutor', 'Educação', NULL),
('Tutor', 'Educação', NULL),
('Monitor', 'Educação', NULL),
('Auxiliar de Sala', 'Educação', NULL),
('Biblioteconomia', 'Educação', NULL),

-- Vendas
('Vendas', 'Vendas', NULL),
('Vendedor', 'Vendas', NULL),
('Representante Comercial', 'Vendas', NULL),
('Gerente de Vendas', 'Vendas', NULL),
('Vendas Externas', 'Vendas', NULL),
('Vendas Internas', 'Vendas', NULL),
('Atendimento ao Cliente', 'Vendas', NULL),
('Telemarketing', 'Vendas', NULL),
('E-commerce', 'Vendas', NULL),
('Vendas B2B', 'Vendas', NULL),
('Vendas B2C', 'Vendas', NULL),
('Inside Sales', 'Vendas', NULL),
('Account Manager', 'Vendas', NULL),

-- Administração
('Administração', 'Administração', NULL),
('RH', 'Administração', NULL),
('Recrutamento e Seleção', 'Administração', NULL),
('Financeiro', 'Administração', NULL),
('Contabilidade', 'Administração', NULL),
('Fiscal', 'Administração', NULL),
('Compras', 'Administração', NULL),
('Secretariado', 'Administração', NULL),
('Assistente Administrativo', 'Administração', NULL),
('Auxiliar Administrativo', 'Administração', NULL),
('Recepcionista', 'Administração', NULL),
('Atendente', 'Administração', NULL),
('Gestão de Pessoas', 'Administração', NULL),
('DP', 'Administração', NULL),
('Folha de Pagamento', 'Administração', NULL),
('Gestão de Projetos', 'Administração', NULL),
('PMO', 'Administração', NULL),

-- Marketing
('Marketing', 'Marketing', NULL),
('Marketing Digital', 'Marketing', NULL),
('Social Media', 'Marketing', NULL),
('SEO', 'Marketing', NULL),
('SEM', 'Marketing', NULL),
('Google Ads', 'Marketing', NULL),
('Facebook Ads', 'Marketing', NULL),
('Content Marketing', 'Marketing', NULL),
('Email Marketing', 'Marketing', NULL),
('Inbound Marketing', 'Marketing', NULL),
('Analytics', 'Marketing', NULL),
('Branding', 'Marketing', NULL),
('Publicidade', 'Marketing', NULL),
('Comunicação', 'Marketing', NULL),
('Jornalismo', 'Marketing', NULL),
('Relações Públicas', 'Marketing', NULL),

-- Engenharia
('Engenharia', 'Engenharia', NULL),
('Engenharia Civil', 'Engenharia', NULL),
('Engenharia Mecânica', 'Engenharia', NULL),
('Engenharia Elétrica', 'Engenharia', NULL),
('Engenharia de Produção', 'Engenharia', NULL),
('Engenharia Química', 'Engenharia', NULL),
('Engenharia de Software', 'Engenharia', NULL),
('Engenharia Ambiental', 'Engenharia', NULL),
('Engenharia de Segurança', 'Engenharia', NULL),
('Técnico em Engenharia', 'Engenharia', NULL),

-- Construção Civil
('Construção Civil', 'Construção Civil', NULL),
('Pedreiro', 'Construção Civil', NULL),
('Carpinteiro', 'Construção Civil', NULL),
('Eletricista', 'Construção Civil', NULL),
('Encanador', 'Construção Civil', NULL),
('Pintor', 'Construção Civil', NULL),
('Arquiteto', 'Construção Civil', NULL),
('Mestre de Obras', 'Construção Civil', NULL),
('Ajudante de Obras', 'Construção Civil', NULL),
('Armador', 'Construção Civil', NULL),
('Gesseiro', 'Construção Civil', NULL),
('Azulejista', 'Construção Civil', NULL),

-- Gastronomia
('Gastronomia', 'Gastronomia', NULL),
('Chef de Cozinha', 'Gastronomia', NULL),
('Cozinheiro', 'Gastronomia', NULL),
('Auxiliar de Cozinha', 'Gastronomia', NULL),
('Confeiteiro', 'Gastronomia', NULL),
('Padeiro', 'Gastronomia', NULL),
('Garçom', 'Gastronomia', NULL),
('Bartender', 'Gastronomia', NULL),
('Barista', 'Gastronomia', NULL),
('Sommelier', 'Gastronomia', NULL),

-- Transporte e Logística
('Transporte', 'Transporte', NULL),
('Motorista', 'Transporte', NULL),
('Motorista de Caminhão', 'Transporte', NULL),
('Entregador', 'Transporte', NULL),
('Motoboy', 'Transporte', NULL),
('Operador de Empilhadeira', 'Transporte', NULL),
('Ajudante de Carga e Descarga', 'Transporte', NULL),
('Despachante', 'Transporte', NULL),
('Agente de Carga', 'Transporte', NULL),

-- Segurança
('Segurança', 'Segurança', NULL),
('Vigilante', 'Segurança', NULL),
('Porteiro', 'Segurança', NULL),
('Segurança Patrimonial', 'Segurança', NULL),
('Segurança do Trabalho', 'Segurança', NULL),
('Técnico em Segurança', 'Segurança', NULL),

-- Beleza e Estética
('Beleza', 'Beleza', NULL),
('Cabeleireiro', 'Beleza', NULL),
('Barbeiro', 'Beleza', NULL),
('Manicure', 'Beleza', NULL),
('Pedicure', 'Beleza', NULL),
('Esteticista', 'Beleza', NULL),
('Massagista', 'Beleza', NULL),
('Maquiador', 'Beleza', NULL),

-- Jurídico
('Jurídico', 'Jurídico', NULL),
('Advogado', 'Jurídico', NULL),
('Assistente Jurídico', 'Jurídico', NULL),
('Estagiário Jurídico', 'Jurídico', NULL),
('Analista Jurídico', 'Jurídico', NULL),

-- Outros
('Atendimento', 'Atendimento', NULL),
('Call Center', 'Atendimento', NULL),
('Suporte Técnico', 'Atendimento', NULL),
('SAC', 'Atendimento', NULL),
('Operador de Telemarketing', 'Atendimento', NULL)
ON CONFLICT DO NOTHING;

-- Verificar quantas tags foram inseridas
SELECT COUNT(*) as total_tags FROM tags;

